stages:
 - build
 - test

Debian:
  image: debian:latest
  stage: build
  before_script:
    - apt-get update -qq
    - env DEBIAN_FRONTEND=noninteractive apt-get install -y -qq make git autoconf automake libtool bison libpam0g-dev libxmlsec1-dev libxml2-utils help2man gtk-doc-tools dblatex valgrind gengetopt libxml2-dbg datefudge
  script:
  - echo "--suppressions=$(pwd)/libpskc/tests/libpskc.supp" >> ~/.valgrindrc
  - make bootstrap
  - make check V=1 || (find . -name test-suite.log -exec cat {} +; exit 1)
  - make dist
  - sha224sum oath-toolkit-*.tar.gz
  artifacts:
    expire_in: 2 weeks
    paths:
      - oath-toolkit-*.tar.gz

Ubuntu:
  image: ubuntu:devel
  stage: build
  before_script:
    - apt-get update -qq
    - env DEBIAN_FRONTEND=noninteractive apt-get install -y -qq make git autoconf automake libtool bison libpam0g-dev libxmlsec1-dev libxml2-utils help2man gtk-doc-tools valgrind gengetopt datefudge
  script:
  - echo "--suppressions=$(pwd)/libpskc/tests/libpskc.supp" >> ~/.valgrindrc
  - make autoreconf
  - ./configure --enable-gcc-warnings --enable-root-tests --enable-valgrind-tests || (cat config.log; exit 1)
  - make check V=1 || (find . -name test-suite.log -exec cat {} +; exit 1)
  - make syntax-check

Mingw64:
  image: debian:latest
  stage: test
  needs: [Debian]
  before_script:
    - apt-get update -qq
    - env DEBIAN_FRONTEND=noninteractive apt-get install -y -qq make mingw-w64 wine wine64 binfmt-support wine-binfmt
    - update-binfmts --enable wine
    - update-binfmts --display
    - mount
    - find /proc/sys/fs/binfmt_misc
  script:
  - tar xfa oath-toolkit-*.tar.gz
  - cd `ls -d oath-toolkit-* | grep -v tar.gz`
  - ./configure --host=x86_64-w64-mingw32
  - make V=1
  - make -C liboath/tests check || (cat liboath/tests/test-suite.log +; exit 1)
  - make -C oathtool/tests check || (cat oathtool/tests/test-suite.log +; exit 1)

Mingw32:
  image: debian:latest
  stage: test
  needs: [Debian]
  before_script:
    - dpkg --add-architecture i386
    - apt-get update -qq
    - env DEBIAN_FRONTEND=noninteractive apt-get install -y -qq make mingw-w64 wine wine32 libwine libwine:i386 binfmt-support wine-binfmt
    - update-binfmts --enable wine
    - update-binfmts --display
    - mount
    - find /proc/sys/fs/binfmt_misc
  script:
  - tar xfa oath-toolkit-*.tar.gz
  - cd `ls -d oath-toolkit-* | grep -v tar.gz`
  - ./configure --host=i686-w64-mingw32
  - make V=1
  - make -C liboath/tests check || (cat liboath/tests/test-suite.log +; exit 1)
  - make -C oathtool/tests check || (cat oathtool/tests/test-suite.log +; exit 1)

CentOS:
  image: centos:latest
  stage: test
  needs: [Debian]
  before_script:
  - yum -y groupinstall "Development Tools"
  - yum -y install libxml2-devel
  script:
  - tar xfa oath-toolkit-*.tar.gz
  - cd `ls -d oath-toolkit-* | grep -v tar.gz`
  - ./configure --enable-gcc-warnings || (cat config.log; exit 1)
  - make check V=1 || (find . -name test-suite.log -exec cat {} +; exit 1)

Alpine:
  image: alpine:latest
  stage: test
  needs: [Debian]
  before_script:
  - echo "ipv6" >> /etc/modules
  - apk update
  - apk add build-base libxml2-dev datefudge
  script:
  - tar xfz oath-toolkit-*.tar.gz
  - cd `ls -d oath-toolkit-* | grep -v tar.gz`
  - ./configure --enable-gcc-warnings || (cat config.log; exit 1)
  - sed -i -e 's,  /\* Outlandishly-long.*,#if 0,;s,  return 0;,#endif\nreturn 0;,' ./oathtool/gl/tests/test-parse-datetime.c
  - make check V=1 || (find . -name test-suite.log -exec cat {} +; exit 1)
